remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: Athang Gupte
description: Game engine developer, AI researcher, C++ evangelist, Networking enthusiast
google_analytics: G-6M93SRD7BZ
